// TARGET: TAIL
global.is_in_editor = false
global.clear_black = -1
global.memory_style = 0
global.wings_style = 0
global.blade_style = 0
global.memory_get = 0
global.wings_get = 0
global.blade_get = 0
global.collect_swapper = 0
global.swapper_used = 0
global.swapper_toggle = 1
global.swapper_backup = 0
global.swapper_style = 0
global.swapper_get = 0