if (stupid_sprite_i_can_only_delete_later_lest_the_cube_shall_whiten != noone) {
	sprite_delete(stupid_sprite_i_can_only_delete_later_lest_the_cube_shall_whiten)
	stupid_sprite_i_can_only_delete_later_lest_the_cube_shall_whiten = noone
}
